version: '2'
services:
  zookeeper:
    image: "zookeeper:3.4"
    ports:
    - "2181:2181"
  kafka:
    image: "ches/kafka"
    links:
    - zookeeper
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=127.0.0.1
      - ZOOKEEPER_IP=zookeeper
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
    ports:
      - "9092:9092"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-platinum:6.2.1
    environment:
      - ELASTIC_PASSWORD=changeme
    ports:
    - "9200:9200"
    - "9300:9300"
  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.1
    ports:
    - "5601:5601"