info:
  component: Importer !

spring.profiles.active: dev

server.port: 8084

management.security.enabled: false

security:
  basic.enabled: false
  user:
    name: admin
    password: admin

logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO
    io.skalogs: INFO

---
spring.profiles: dev

process.active: true
process.nbConsummer: 1
process.defaultRouteType.outType: "ELASTICSEARCH"
process.adminUrl: "http://localhost:8090"

validator.maxFields: 100
validator.maxSize: 20000
validator.maximumInThePastAllowed: 1
validator.maximumInTheFutureAllowed: 1
validator.mandatoryFields:
- "@timestamp"
- "project"
- "type"
- "project"
validator.blacklistType:
- "auditd"
- "kernel"
validator.whitelistType:
validator.cardinalityFieldChecks:

elasticsearch.host: localhost
elasticsearch.port: 9200
elasticsearch.clusterName: docker-cluster
elasticsearch.serviceElasticsearchUsername: elastic
elasticsearch.serviceElasticsearchPassword: changeme
elasticsearch.clientTransportPingTimeout: 10
elasticsearch.clientNodesSamplerInterval: 10
elasticsearch.customIndexPrefix: "index-dev"

bufferElasticsearch.maxElements: 10
bufferElasticsearch.maxSizeInBytes: 10000
bufferElasticsearch.maxTime: 1

kafka.topic: processtopic
kafka.bootstrapServers: localhost:9092
kafka.pollingTime: 1000
kafka.pollRecord: 50
kafka.groupId: importer

spring.h2.console.enabled: true

spring.datasource:
  platform: h2
  driverClassName: org.h2.Driver
  url: jdbc:h2:mem:skalogs;MODE=PostgreSQL
  username: fu
  password: fu

spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
spring.datasource.platform: h2
spring.jpa:
  open-in-view: false
  hibernate:
    ddl-view: none
    naming-strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy
    hbm2ddl.auto: update
  show_sql: false
  properties:
    hibernate.cache.use_second_level_cache: false
    hibernate.cache.use_query_cache: false
    hibernate.generate_statistics: false
